
create database BCCR_API
use BCCR_API

BEGIN TRANSACTION;
BEGIN TRY
    CREATE TABLE TipoCambio (
        COD_INDICADORINTERNO	VARCHAR(255)	NOT NULL,
        DES_FECHA				VARCHAR(255)	NOT NULL,
        NUM_VALOR				VARCHAR(255)	NOT NULL,
    );
    COMMIT;
END TRY
BEGIN CATCH
    ROLLBACK;
END CATCH;
